
CREATE EVENT IF NOT EXISTS excluir_reservas_antigas

    ON SCHEDULE EVERY 21 DAY

    STARTS CURRENT_TIMESTAMP + INTERVAL 1 MINUTE

    ON COMPLETION PRESERVE

    ENABLE

DO
    DELETE FROM schedule
    WHERE dateEnd < NOW() - INTERVAL 1 MONTH;

